name: running_app_flutter
description: Flutter application for running. Uses Provider, Location, Yandex Map Kit, Firebase.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yandex_mapkit: ^2.0.5
  location: ^4.2.0
  provider: ^6.0.2
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_core: ^1.12.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true